# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('long_link', models.CharField(max_length=200)),
                ('short_link', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
