# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170628_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='date',
            new_name='date_added',
        ),
    ]
